---
title: "Supplemental Analyses"
author: "Katherine Anne Mason"
date: "2024-03-10"
output: html_document
---

```{r, Load packages}

library(readxl)
library(writexl)
library(lme4)
library(nlme)
library(ordinal)
library(carData)
library(car)
library(lmerTest)
library(tidyverse)
library(lsmeans)
library(stats)
library(sjPlot)
library(sjmisc)
library(ggplot2)
library(glmmTMB) 
library(MASS)
library(psych)
library(ltm)
library(Hmisc)
library(broom)
library(knitr)
library(EMAtools)
library(sjstats)
library(effectsize)

```


###### IDEOLOGY X COUNTRY DECOMPOSTITION ######

```{r, Import and prepare data}

# Import data sets

df_17 <- read.csv("Syst_Sanct_17_Data.csv")

# Center age, education, and income.

mean(df_17$ide, na.rm = TRUE)
df_17$ide_c <- df_17$ide - 51.88034
mean(df_17$ide_c, na.rm = TRUE) 

mean(df_17$Age, na.rm = TRUE)
df_17$age_c <- df_17$Age - 41.71985
mean(df_17$age_c, na.rm = TRUE) 

mean(df_17$Income, na.rm = TRUE)
df_17$income_c <- df_17$Income - 4.238184
mean(df_17$income_c, na.rm = TRUE)

mean(df_17$Edu, na.rm = TRUE)
df_17$edu_c <- df_17$Edu - 2.848025
mean(df_17$edu_c, na.rm = TRUE) 

# Liberal and conservative for simple effects.
df_17$ide_low <- df_17$ide_c - (-30)
df_17$ide_high <- df_17$ide_c - (30)

# Make the belief data set for the full sample 

df17_Belief <- pivot_longer(df_17, cols = c("Belief1", "Belief2", "Belief3", "Belief4"), names_to = "BeliefItem", values_to = "Belief")

df17_Belief

# Make the policy data set for the full sample

df17_Policy <- pivot_longer(df_17, cols = c("Policy1", "Policy2", "Policy3", "Policy4", "Policy5", "Policy6", "Policy7", "Policy8", "Policy9"), names_to = "PolicyItem", values_to = "Policy")

df17_Policy

# Make sure US the reference country.

df17_Belief$Country <- as.factor(df17_Belief$Country)
df17_Policy$Country <- as.factor(df17_Policy$Country)
df_17$Country <- as.factor(df_17$Country)

df17_Belief$Country <- relevel(df17_Belief$Country, ref = 'USA')
df17_Policy$Country <- relevel(df17_Policy$Country, ref = 'USA')
df_17$Country <- relevel(df_17$Country, ref = 'USA')

# Standardize data sets

zdf_17 <- as.data.frame(scale(df_17[, c("ide_c", "Age", "age_c", "Edu", "edu_c", "Income", "income_c")]), center = T)

zdf_17 <- cbind(df_17[, c("ResponseId", "Country", "cond_effects", "gend_effects", "Poland_E", "Sweden_E",	"Chile_E", "Netherlands_E",	"UK_E",	"Italy_E", "Nigeria_E",	"Germany_E", "France_E", "Japan_E",	"Russia_E",	"Israel_E",	"Brazil_E",	"Canada_E",	"Switzerland_E",	"Belgium_E", "SHAREcc", "WEPTcc"), drop = FALSE], as.data.frame(zdf_17))

# High and low ideology

zdf_17$ide_low <- zdf_17$ide_c - (-1.26) # Equal to 30 points in unstandardized units
zdf_17$ide_high <- zdf_17$ide_c - (1.26) # Equal to 30 points in unstandardized units

# Belief 

z_df17_Belief <- as.data.frame(scale(df17_Belief[, c("ide_c", "Age", "age_c", "Edu", "edu_c", "Income", "income_c", "Belief")]), center = T)

z_df17_Belief <- cbind(df17_Belief[, c("ResponseId", "Country", "BeliefItem", "cond_effects", "gend_effects", "Poland_E", "Sweden_E",	"Chile_E", "Netherlands_E",	"UK_E",	"Italy_E", "Nigeria_E",	"Germany_E", "France_E", "Japan_E",	"Russia_E",	"Israel_E",	"Brazil_E",	"Canada_E",	"Switzerland_E",	"Belgium_E"), drop = FALSE], as.data.frame(z_df17_Belief))

z_df17_Belief

# High and low ideology 

z_df17_Belief$ide_low <- z_df17_Belief$ide_c - (-1.26) 
z_df17_Belief$ide_high <- z_df17_Belief$ide_c - (1.26) 

# Policy

z_df17_Policy <- as.data.frame(scale(df17_Policy[, c("ide_c","Age", "age_c", "Edu", "edu_c", "Income", "income_c","Policy")]), center = T)

z_df17_Policy <- cbind(df17_Policy[, c("ResponseId", "Country", "PolicyItem", "cond_effects", "gend_effects", "Poland_E", "Sweden_E",	"Chile_E", "Netherlands_E",	"UK_E",	"Italy_E", "Nigeria_E",	"Germany_E", "France_E", "Japan_E",	"Russia_E",	"Israel_E",	"Brazil_E",	"Canada_E",	"Switzerland_E",	"Belgium_E"), drop = FALSE], as.data.frame(z_df17_Policy))

z_df17_Policy

# High and low ideology

z_df17_Policy$ide_low <- z_df17_Policy$ide_c - (-1.26) 
z_df17_Policy$ide_high <- z_df17_Policy$ide_c - (1.26) 


```

# BELIEF IN CLIMATE CHANGE

```{r, Function, effect of ideology on belief for each country}

# Define a function 
fit_and_extract_ci <- function(country_name, data) {
  
  # Country reference level
  data$Country <- relevel(data$Country, ref = country_name)
  
  # Fit the model
  model <- lme(Belief ~ ide_c*cond_effects*Country + 
                gend_effects + age_c + edu_c + income_c,
                random = ~ 1 | BeliefItem,
                data = data,
                method = "REML",
                na.action = na.omit,
                control = lmeControl(msMaxIter = 1000))
  
  # Extract confidence intervals
  ci <- intervals(model, which = "fixed")
  ci_frame <- data.frame(ci$fixed) 
  result <- ci_frame[2, ] 
  
  return(result)
}

# Data frame to store the results
Belief_Ide <- data.frame(
  country = character(0),
  lower = numeric(0),
  est. = numeric(0),
  upper = numeric(0)
)

country_names <- unique(z_df17_Belief$Country)

# Loop through each country and compute estimates and CIs
for (country_name in country_names) {
  ci <- fit_and_extract_ci(country_name, z_df17_Belief)
  Belief_Ide <- bind_rows(Belief_Ide, data.frame(country = country_name, ci))
}

# Make country the index variable
rownames(Belief_Ide) <- z_df17_Belief$country

Belief_Ide

# Export the table as a data set.
# write.xlsx(Belief_Ide, file = "Belief_Ide.xlsx")

```

# SUPPORT FOR POLICY

```{r, Function, effect of ideology on policy support for each country}

# Define a function 
fit_and_extract_ci <- function(country_name, data) {

    # Country reference level
    data$Country <- relevel(data$Country, ref = country_name)
  
  # Fit the model
  model <- lme(Policy ~ ide_c*cond_effects*Country + 
                gend_effects + age_c + edu_c + income_c, 
                random = ~ 1 | PolicyItem,
                data = data,
                method = "REML",
                na.action = na.omit,
                control = lmeControl(msMaxIter = 1000))
  
  # Extract confidence intervals
  ci <- intervals(model, which = "fixed")
  ci_frame <- data.frame(ci$fixed) 
  result <- ci_frame[2, ] 
  
  return(result)
}

# Create a data frame to store the results
Policy_Ide <- data.frame(
  country = character(0),
  lower = numeric(0),
  est. = numeric(0),
  upper = numeric(0)
)

country_names <- unique(z_df17_Policy$Country)

# Loop through each country and compute estimates and CIs
for (country_name in country_names) {
  ci <- fit_and_extract_ci(country_name, z_df17_Policy)
  Policy_Ide <- bind_rows(Policy_Ide, data.frame(country = country_name, ci))
}

# Make country the index variable
rownames(Policy_Ide) <- z_df17_Policy$country

Policy_Ide

# Export the table as a data set.
# write.xlsx(Policy_Ide, file = "Policy_Ide.xlsx")

```

# SHARING INTENTIONS

```{r, Function, effect of ideology on sharing for each country}

# Define a function 
fit_and_extract_ci <- function(country_name, data) {
  
  # Country reference level
  data$Country <- relevel(data$Country, ref = country_name)
  
  # Fit the model
  model <- glm(SHAREcc ~ cond_effects*Country*ide_c + gend_effects + age_c + edu_c + income_c, data = data, family = binomial(link = logit))
  
  # Extract estimates
  est <- coef(model)["ide_c"]
  
  # Extract confidence intervals
  ci <- confint(model, "ide_c")
  
  # CIs into data frame 
  ci <- as.data.frame(t(ci))
  colnames(ci) <- c("lower", "upper")
  
  return(list(est = est, ci = ci))
}

# Create a data frame to store the results
Share_Ide <- data.frame(
  country = character(0),
  lower = numeric(0),
  est = numeric(0),
  upper = numeric(0)
)

country_names <- unique(zdf_17$Country)

# Loop through each country and compute estimates and CIs
for (country_name in country_names) {
  results <- fit_and_extract_ci(country_name, zdf_17)
  est <- results$est
  ci <- results$ci
  Share_Ide <- bind_rows(Share_Ide, data.frame(country = country_name, est, ci))
}

# Make country the index variable
rownames(Share_Ide) <- zdf_17$country

# Standardize 

Share_Ide$stand_lower <- Share_Ide$lower %>%
  logoddsratio_to_r()

Share_Ide$stand <- Share_Ide$est %>%
  logoddsratio_to_r()

Share_Ide$stand_upper <- Share_Ide$upper %>%
  logoddsratio_to_r()

Share_Ide

# Export the table as a data set.
# write.csv(Share_Ide, file = "Share_Ide.csv")

```

# ACTION

```{r, Function, effect of condition on action}

# Define a function to fit the model and extract confidence intervals
fit_and_extract_ci <- function(country_name, data) {
  
  # Set the country as the reference level
  data$Country <- relevel(data$Country, ref = country_name)
  
  # Fit the linear model
  model <- lm(WEPTcc ~ ide_c * cond_effects * Country + 
                gend_effects + age_c + edu_c + income_c,
                data = data)
  
  # Extract estimates
  est <- coef(model)["ide_c"]
  
  # Extract confidence intervals
  ci <- as.data.frame(confint(model, "ide_c"))
  colnames(ci) <- c("lower", "upper")
  
  return(list(est = est, ci = ci))
}

# Create a data frame to store the results
Action_Ide <- data.frame(
  country = character(0),
  lower = numeric(0),
  est = numeric(0),
  upper = numeric(0)
)

# List of country names 
country_names <- unique(zdf_17$Country)

# Loop through each country and compute estimates and CIs
for (country_name in country_names) {
  results <- fit_and_extract_ci(country_name, zdf_17)
  est <- results$est
  ci <- results$ci
  Action_Ide <- bind_rows(Action_Ide, data.frame(country = country_name, est, ci))
}

# Make country the index variable
rownames(Action_Ide) <- zdf_17$country

Action_Ide

# Export the table as a data set.
# write.csv(Action_Ide, file = "Action_Ide.csv")

```


###### POLITICAL CONGRUENCY ANALYSES ###### 

```{r, Prepare belief and policy congruency data set}

congruency_df <- read.csv('Congruency.csv')

# In the regular data set, get rid of unwanted variables

congruency_df <- subset(congruency_df, select=c('PowerShift', "ResponseId", "Country", "cond", "condName", "cond_effects", "ide_c", "Age", "age_c", "Income", "income_c", "Edu", "edu_c", "gend_effects", "ide_Bin", "Congruence", "SHAREcc", "WEPTcc", "Belief1", "Belief2", "Belief3", "Belief4", "Policy1", "Policy2", "Policy3", "Policy4", "Policy5", "Policy6", "Policy7", "Policy8", "Policy9"))

congruency_df

# Standardize the regular data set

zcongruency_df <- as.data.frame(scale(congruency_df[, c("ide_c", "age_c", "edu_c", "income_c", "WEPTcc")]), center = T)

zcongruency_df <- cbind(congruency_df[, c("ResponseId", "Country", "cond_effects", "gend_effects", 'PowerShift', "Congruence", 'ide_Bin', "SHAREcc"), drop = FALSE], as.data.frame(zcongruency_df))

# High and low ideology

zcongruency_df$ide_low <- zcongruency_df$ide_c - (-1.26) # Equal to 30 points in unstandardized units
zcongruency_df$ide_high <- zcongruency_df$ide_c - (1.26) # Equal to 30 points in unstandardized units

# Make belief data set long 

df_belief_congruence <- pivot_longer(congruency_df, cols = c("Belief1", "Belief2", "Belief3", "Belief4"), names_to = "BeliefItem", values_to = "Belief")

df_belief_congruence

# Standardize the belief data set

zdf_belief_congruence <- as.data.frame(scale(df_belief_congruence[, c("ide_c", "age_c", "edu_c", "income_c", "Belief")]), center = T)

zdf_belief_congruence <- cbind(df_belief_congruence[, c("ResponseId", "Country", "BeliefItem", "cond_effects", "gend_effects", "ide_Bin", "Congruence"), drop = FALSE], as.data.frame(zdf_belief_congruence))

# High and low ideology

zdf_belief_congruence$ide_low <- zdf_belief_congruence$ide_c - (-1.26) 
zdf_belief_congruence$ide_high <- zdf_belief_congruence$ide_c - (1.26) 


# Make policy data set long

df_policy_congruence <- pivot_longer(congruency_df, cols = c("Policy1", "Policy2", "Policy3", "Policy4", "Policy5", "Policy6", "Policy7", "Policy8", "Policy9"), names_to = "PolicyItem", values_to = "Policy")

df_policy_congruence

# Standardize the policy data set

zdf_policy_congruence <- as.data.frame(scale(df_policy_congruence[, c("ide_c", "age_c", "edu_c", "income_c", "Policy")]), center = T)

zdf_policy_congruence <- cbind(df_policy_congruence[, c("ResponseId", "Country", "PolicyItem", "cond_effects", "gend_effects", "ide_Bin","Congruence"), drop = FALSE], as.data.frame(zdf_policy_congruence))

# High and low ideology

zdf_policy_congruence$ide_low <- zdf_policy_congruence$ide_c - (-1.26) 
zdf_policy_congruence$ide_high <- zdf_policy_congruence$ide_c - (1.26) 

```

# CONGRUENCY ANALYSES BELIEF

```{r, Ideology X Condition X Country X Congruency on Belief Omnibus}

Congruency_Belief1 <- lmer(Belief ~cond_effects*ide_c*Congruence*Country + (1 | BeliefItem), data = df_belief_congruence)
summary(Congruency_Belief1)
anova(Congruency_Belief1)

# Add covariates

Congruency_Belief2 <- lmer(Belief ~cond_effects*ide_c*Congruence*Country + gend_effects + age_c + edu_c + income_c + (1 | BeliefItem), data = df_belief_congruence)
summary(Congruency_Belief2)

Congruency_Belief2_table <- anova(Congruency_Belief2) %>%
                      round(., 4) %>%
                      kable()

Congruency_Belief2_table

  
```

# CONGRUENCY ANALYSES POLICY 

```{r, Ideology X Condition X Country X Congruency on Policy Omnibus}

Congruency_Policy1 <- lmer(Policy ~ide_c*cond_effects*Congruence*Country + (1 | PolicyItem), data = df_policy_congruence)
summary(Congruency_Policy1)
anova(Congruency_Policy1)

# Add covariates

Congruency_Policy2 <- lmer(Policy ~cond_effects*ide_c*Congruence*Country + gend_effects + age_c + edu_c + income_c + (1 | PolicyItem), data = df_policy_congruence)
summary(Congruency_Policy2)

Congruency_Policy1_table <- anova(Congruency_Policy2) %>%
                      round(., 4) %>%
                      kable()

Congruency_Policy1_table

```

# CONGRUENCY ANALYSIS SHARING

```{r, Ideology X Condition X Country X Congruency on Sharing Omnibus}

# SAS 

```

# CONGRUENCY ANALYSIS ACTION

```{r, Ideology X Condition X Country X Congruency on Action Omnibus}

Congruency_Action1 <- lm(WEPTcc ~ide_c*cond_effects*Congruence*Country, data = congruency_df)
summary(Congruency_Action1)

# Add covariates

Congruency_Action2 <- lm(WEPTcc ~ cond_effects*ide_c*Congruence*Country + gend_effects + age_c + edu_c + income_c, data = congruency_df)
summary(Congruency_Action2)

Congruency_Action2_table <- car::Anova(Congruency_Action2, type = "3") %>%
                      round(., 2) %>%
                      kable()

Congruency_Action2_table

```

###### EFFECT OF GDP, CRI, EPI, CLIMATE CHANGE CONCERN, AND BELEIF POLARIZATION ON DVS ######

```{r, Import and prepare data}

mechanism <- read.csv("Mechanism.csv")
mechanism

# Standardize 

Zmechanism <- data.frame(
                         Zgdp = scale(mechanism$GDP, center = TRUE, scale = TRUE),
                         Zcri = scale(mechanism$CRI, center = TRUE, scale = TRUE),
                         Zepi = scale(mechanism$EPI, center = TRUE, scale = TRUE),
                         ZccCONCERN = scale(mechanism$ccCONCERN, center = TRUE, scale = TRUE),
                         Zabs_Dif_Belief = scale(mechanism$abs_Dif_Belief, center = TRUE, scale = TRUE)
                         )

Zmechanism <- data.frame(cbind(mechanism, Zmechanism))
                                                
Zmechanism

```

```{r, Mechanisms}

# Belief 

Mech_Belief <- lm(Belief_Est ~ Zgdp + Zcri + Zepi + ZccCONCERN + Zabs_Dif_Belief, data = Zmechanism)
summary(Mech_Belief)

Mech_Belief_table <- summary(Mech_Belief)$coefficients %>%
                      round(., 3) %>%
                      kable()

Mech_Belief_table

# Policy

Mech_Policy <- lm(Policy_Est ~ Zgdp + Zcri + Zepi + ZccCONCERN + Zabs_Dif_Belief, data = Zmechanism)
summary(Mech_Policy)

# Make a table

Mech_Policy_table <- summary(Mech_Policy)$coefficients %>%
                      round(., 2) %>%
                      kable()

Mech_Policy_table

# Sharing

Mech_Share <- lm(Share_Est ~ Zgdp + Zcri + Zepi + ZccCONCERN + Zabs_Dif_Belief, data = Zmechanism)
summary(Mech_Share)

# Make a table

Mech_Share_table <- summary(Mech_Share)$coefficients %>%
                      round(., 2) %>%
                      kable()

Mech_Share_table


# Action 

Mech_Action <- lm(Action_Est ~ Zgdp + Zcri + Zepi + ZccCONCERN + Zabs_Dif_Belief, data = Zmechanism)
summary(Mech_Action)

# Make a table

Mech_Action_table <- summary(Mech_Action)$coefficients %>%
                      round(., 3) %>%
                      kable()

Mech_Action_table

```
