---
title: "USA Analyses"
author: "Katie Mason"
date: "2023-07-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, Load packages}

library(readxl) 
library(writexl)
library(lme4)
library(nlme)
library(ordinal)
library(carData)
library(car)
library(lmerTest)
library(tidyverse)
library(lsmeans)
library(stats)
library(sjPlot)
library(sjmisc)
library(ggplot2)
library(glmmTMB) 
library(MASS)
library(psych)
library(ltm)
library(Hmisc)
library(broom)
library(knitr)
library(EMAtools)
library(sjstats)
library(effectsize)

```

```{r, Import and prepare data}

df_USA <- read.csv("Syst_Sanct_USA_Data.csv")

table(df_USA$Gender)
table(df_USA$condName)

# Re-center

mean(df_USA$ide, na.rm = TRUE)
df_USA$ide_c <- df_USA$ide - 55.27103
mean(df_USA$ide_c, na.rm = TRUE) 

mean(df_USA$Age, na.rm = TRUE)
df_USA$age_c <- df_USA$Age - 46.14511
mean(df_USA$age_c, na.rm = TRUE) 

mean(df_USA$Income, na.rm = TRUE)
df_USA$income_c <- df_USA$Income - 4.534954
mean(df_USA$income_c, na.rm = TRUE)

mean(df_USA$Edu, na.rm = TRUE)
df_USA$edu_c <- df_USA$Edu - 2.911722
mean(df_USA$edu_c, na.rm = TRUE) 

# Liberal and conservative for simple effects.
df_USA$ide_low <- df_USA$ide_c - (-30)
df_USA$ide_high <- df_USA$ide_c - (30)

# Make the belief data set 

USA_belief <- pivot_longer(df_USA, cols = c("Belief1", "Belief2", "Belief3", "Belief4"), names_to = "BeliefItem", values_to = "Belief")

USA_belief

# Make the policy data set 

USA_policy <- pivot_longer(df_USA, cols = c("Policy1", "Policy2", "Policy3", "Policy4", "Policy5", "Policy6", "Policy7", "Policy8", "Policy9"), names_to = "PolicyItem", values_to = "Policy")

USA_policy

# Standardize data sets

zdf_USA <- as.data.frame(scale(df_USA[, c("BELIEFcc", 'POLICYcc', "WEPTcc","ide_c", "Age", "age_c", "Edu", "edu_c", "Income", "income_c")]), center = T)

zdf_USA <- cbind(df_USA[, c("ResponseId", "cond_effects", "gend_effects","SHAREcc"), drop = FALSE], as.data.frame(zdf_USA))

# High and low ideology

zdf_USA$ide_low <- zdf_USA$ide_c - (-1.26) # Equal to 30 points in unstandardized units
zdf_USA$ide_high <- zdf_USA$ide_c - (1.26) # Equal to 30 points in unstandardized units

z_USA_belief <- as.data.frame(scale(USA_belief[, c("ide_c", "Age", "age_c", "Edu", "edu_c", "Income", "income_c","Belief")]), center = T)

z_USA_belief <- cbind(USA_belief[, c("ResponseId", "BeliefItem", "cond_effects", "gend_effects"), drop = FALSE], as.data.frame(z_USA_belief))

z_USA_belief

z_USA_belief$ide_low <- z_USA_belief$ide_c - (-1.26) 
z_USA_belief$ide_high <- z_USA_belief$ide_c - (1.26) 

z_USA_policy <- as.data.frame(scale(USA_policy[, c("ide_c", "Age", "age_c", "Edu", "edu_c", "Income", "income_c","Policy")]), center = T)

z_USA_policy <- cbind(USA_policy[, c("ResponseId", "Country", "PolicyItem", "cond_effects", "gend_effects"), drop = FALSE], as.data.frame(z_USA_policy))

z_USA_policy

z_USA_policy$ide_low <- z_USA_policy$ide_c - (-1.26) 
z_USA_policy$ide_high <- z_USA_policy$ide_c - (1.26) 

```

## BELIEF ##

```{r, Effect of condition on belief, moderated by ideology}

# Without covariates 

USBelief_1.1 <- lmer(Belief ~cond_effects*ide_c + (1 | BeliefItem), data = USA_belief)
print(summary(USBelief_1.1))

# Standardized 

USBelief_1.2 <- lmer(Belief ~cond_effects*ide_c + (1 | BeliefItem), data = z_USA_belief)
print(summary(USBelief_1.2))

# Add covariates

USBelief_1.3 <- lmer(Belief ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1 | BeliefItem), data = USA_belief)
summary(USBelief_1.3)

# Extract coefficients and make a table

USBelief_1.3_table <- summary(USBelief_1.3)$coefficients %>%
                      round(., 4) %>%
                      kable()

USBelief_1.3_table

# Standardized 

USBelief_1.4 <- lmer(Belief ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1 | BeliefItem), data = z_USA_belief)
summary(USBelief_1.4)

# Extract coefficients and make a table

USBelief_1.4_table <- summary(USBelief_1.4)$coefficients %>%
                      round(., 3) %>%
                      kable()
USBelief_1.4_table

# Effect size conversion

ide_d <- 2 * 0.348 / sqrt(1 - 0.348	^2)
ide_d 
# -0.74

cond_d <- 2 * 0.1806 / sqrt(1 - 0.1806^2)
cond_d 
#0.37

int_d <- 2 * 0.015 / sqrt(1 - 0.015^2)
int_d
# -0.03

```

```{r, Belief graph USA}

#Rename condition so that neater:

df_USA$condName2[df_USA$condName == 'Control'] <- 'Control'
df_USA$condName2[df_USA$condName == 'SystemJust'] <- 'System Sanctioned Change'

df_USA$condName2 

BeliefUSA_Graph <- lm(BELIEFcc ~ ide*condName2 + gend_effects + age_c + edu_c + income_c, data = df_USA)
print(summary(BeliefUSA_Graph))

set_theme(theme_classic())

graph1 <- plot_model(
  BeliefUSA_Graph, 
  type = "eff", 
  terms = c("ide", "condName2"), 
  mdrt.values = 'meansd', 
  title = "A. Belief in Climate Change", 
  show.data = TRUE, 
  colors = c("darkgoldenrod", "maroon"),
  dot.size = .5,
  axis.title = '',
  axis.labels = 'Ideology',
  legend.title = 'Condition',
  line.size = .9,
  jitter = TRUE,
  ci.lvl = .95 # CI
)

graph1 <- graph1 +
  labs(x = "") +
  scale_x_continuous(limits = c(15, 87), breaks = c(20, 80), labels = c("Liberal/
Left Wing", "Conservative/
Right Wing")) +
  scale_y_continuous(limits = c(0, 100)) +
  theme(
    plot.margin = unit(c(0, 4.5, 0, 4.5), "cm"),
    legend.position = "none",  # Remove legend
    plot.title = element_text(size = 14, face = "bold", color = "black"),
    axis.title.x = element_text(size = 14, color = "black"),  
    axis.title.y = element_text(size = 14, color = "black"),  
    axis.text.x = element_text(size = 14, color = "black"),  
    axis.text.y = element_text(size = 14, color = "black")   
  )

graph1

# ggsave("CCBeliefGraphR_USA.pdf", plot = graph1, width = 8, height = 6, units = "in", dpi = 300)

```

## POLICY ##

```{r, Effect of condition on support for policy, moderated by ideology}

USPolicy_1.1 <- lmer(Policy ~ cond_effects*ide_c + (1 | PolicyItem), data = USA_policy)
print(summary(USPolicy_1.1))

# Standardize

USPolicy_1.2 <- lmer(Policy ~ cond_effects*ide_c + (1 | PolicyItem), data = z_USA_policy)
print(summary(USPolicy_1.2))

# Add covariates 

USPolicy_1.3 <- lmer(Policy ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1 | PolicyItem), data = USA_policy)
summary(USPolicy_1.3)

# Extract coefficients and make a table

USPolicy_1.3_table <- summary(USPolicy_1.3)$coefficients %>%
                      round(., 3) %>%
                      kable()

USPolicy_1.3_table

# Standardized 

USPolicy_1.4 <- lmer(Policy ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1 | PolicyItem), data = z_USA_policy)
summary(USPolicy_1.4)

# Extract coefficients and make a table

USPolicy_1.4_table <- summary(USPolicy_1.4)$coefficients %>%
                      round(., 3) %>%
                      kable()

USPolicy_1.4_table

# Effect size conversion

# lme.dscore(USPolicy_1.3, USA_policy,"lme4")

ide_d <- 2 * 0.2343 / sqrt(1 - 0.2343	^2)
ide_d 
# -0.4820173

cond_d <- 2 * 0.1234 / sqrt(1 - 0.1234^2)
cond_d 
#0.2487008

int_d <- 2 * 0.0244 / sqrt(1 - 0.0244^2)
int_d
# -0.04881453

```

```{r, Policy graph USA}

#Rename cond so that neater:

df_USA$condName2[df_USA$condName == 'Control'] <- 'Control'
df_USA$condName2[df_USA$condName == 'SystemJust'] <- 'System Justification'

set_theme(theme_classic())

PolicyUSA_graph <- lm(POLICYcc ~ide + condName2 + ide*condName2 + gend_effects + age_c + edu_c + income_c, data = df_USA)

graph2 <- plot_model(
  PolicyUSA_graph, 
  type = "eff", 
  terms = c("ide", "condName2"), 
  mdrt.values = 'meansd', 
  title = "B. Support for Pro-environmental Policies", 
  show.data = TRUE, 
  colors = c("darkgoldenrod", "maroon"),
  dot.size = .5,
  axis.title = '',
  axis.labels = 'Ideology',
  legend.title = 'Condition',
  line.size = .9,
  jitter = TRUE,
  ci.lvl = .95 # CI
)

graph2 <- graph2 +
  labs(x = "") +
  scale_x_continuous(limits = c(15, 87), breaks = c(20, 80), labels = c("Liberal/
Left Wing", "Conservative/
Right Wing")) +
  scale_y_continuous(limits = c(0, 100)) +
  theme(
    plot.margin = unit(c(0, 4.5, 0, 4.5), "cm"),
    legend.position = "none",  # Remove legend
    plot.title = element_text(size = 14, face = "bold", color = "black"),
    axis.title.x = element_text(size = 14, color = "black"),  
    axis.title.y = element_text(size = 14, color = "black"),  
    axis.text.x = element_text(size = 14, color = "black"),  
    axis.text.y = element_text(size = 14, color = "black")   
  )

graph2


# ggsave("CCPolicyGraphR_USA.pdf", plot = graph2, width = 8, height = 6, units = "in", dpi = 300)

```

## SHARING ##

```{r, Effect of condition on sharing intentions, moderated by ideology}

df_USA$SHAREcc <- as.factor(df_USA$SHAREcc)

# Without covariates 

USShare_1.1 <- glm(SHAREcc ~ cond_effects*ide_c, data = df_USA, family = binomial(link = "logit"))
summary(USShare_1.1)

# Add covariates 

USShare_1.2 <- glm(SHAREcc ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c, data = df_USA, family = binomial(link = logit))
summary(USShare_1.2)

# Extract coefficients and make a table

USShare_1.2_table <- summary(USShare_1.2)$coefficients %>%
                      round(., 4) %>%
                      kable()

USShare_1.2_table

# Effect size conversion - r

USShare_1.2_r <- summary(USShare_1.2)$coefficients %>%
                    logoddsratio_to_r()  %>%
                    round(., 2) %>%
                    kable()

USShare_1.2_r

# Effect size conversion - d

ide_d <- oddsratio_to_d(-0.0019, log = TRUE)

cond_d <- oddsratio_to_d(0.4634, log = TRUE)

interaction_d <- oddsratio_to_d(0.0013, log = TRUE)

ide_d #-0.001
cond_d #0.26
interaction_d #0.001

summary(USShare_1.2)

```

```{r, Sharing graph}

set_theme(theme_classic())

#Rename condition so that neater:
df_USA$condName2[df_USA$condName == 'Control'] <- 'Control'
df_USA$condName2[df_USA$condName == 'SystemJust'] <- 'System Justification'

ShareUSA_graph <- glm(SHAREcc ~ ide*condName2 + gend_effects + age_c + edu_c + income_c, data = df_USA, family = binomial(link = logit))
summary(ShareUSA_graph)

graph3 <- plot_model(
  ShareUSA_graph, 
  type = "eff", 
  terms = c("ide", "condName2"), 
  mdrt.values = 'meansd', 
  title = "C. Social Media Sharing Intentions", 
  show.data = TRUE, 
  colors = c("darkgoldenrod", "maroon"),
  dot.size = .5,
  axis.title = '',
  axis.labels = 'Ideology',
  legend.title = 'Condition',
  line.size = 1.0,
  ylim = c(50, 100),
  jitter=.07,
  ci.lvl = .95,
)

graph3 <- graph3 +
  labs(x = "") +
  scale_x_continuous(limits = c(15, 87), breaks = c(20, 80), labels = c("Liberal/
Left Wing", "Conservative/
Right Wing")) +
  scale_y_continuous(limits = c(0, 1)) +
  theme(
    plot.margin = unit(c(0, 4.5, 0, 4.5), "cm"),
    legend.position = "none",  # Remove legend
    plot.title = element_text(size = 14, face = "bold", color = 'black'),  
    axis.title.x = element_text(size = 14, color = 'black'), 
    axis.title.y = element_text(size = 14, color = 'black'),  
    axis.text.x = element_text(size = 14, color = 'black'),  
    axis.text.y = element_text(size = 14, color = 'black')   
  )

graph3

# ggsave("CCSharingGraphR_USA.pdf", plot = graph3, width = 8, height = 6, units = "in", dpi = 300)

```

## ACTION ##

```{r, Effect of condition on action, moderated by ideology}

# No covariates 

USAction_1.1 <- lm(WEPTcc ~ cond_effects*ide_c, data = df_USA)
summary(USAction_1.1)

# Standardized

USAction_1.2 <- lm(WEPTcc ~ cond_effects*ide_c, data = zdf_USA)
summary(USAction_1.2)

# Add covariates

USAction_1.3 <- lm(WEPTcc ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c, data = df_USA)
summary(USAction_1.3)

# Extract coefficients and make a table

USAction_1.3_table <- summary(USAction_1.3)$coefficients %>%
                      round(., 3) %>%
                      kable()

USAction_1.3_table

# Standardized

USAction_1.4 <- lm(WEPTcc ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c, data = zdf_USA)
summary(USAction_1.3)

# Extract coefficients and make a table

USAction_1.4_table <- summary(USAction_1.4)$coefficients %>%
                      round(., 2) %>%
                      kable()

USAction_1.4_table

```


