---
title: "Analyses Involving All 63 Countries"
author: "Katherine Anne Mason"
date: "2024-01-15"
output: html_document
---

```{r, Load packages}

library(readxl)
library(writexl)
library(lme4)
library(nlme) 
library(ordinal)
library(carData)
library(car)
library(lmerTest)
library(tidyverse)
library(lsmeans)
library(stats)
library(sjPlot)
library(sjmisc)
library(ggplot2)
library(glmmTMB) 
library(MASS)
library(psych)
library(ltm)
library(Hmisc)
library(broom)
library(knitr)
library(tools)
library(EMAtools)
library(sjstats)
library(effectsize)

```

```{r, Import and prepare data}

dfAll <- read.csv("Syst_Sanct_63_Data.csv")

# Center 

mean(dfAll$ide, na.rm = TRUE)
dfAll$ide_c <- dfAll$ide - 52.47306
mean(dfAll$ide_c, na.rm = TRUE) 

mean(dfAll$Age, na.rm = TRUE)
dfAll$age_c <- dfAll$Age - 39.13618
mean(dfAll$age_c, na.rm = TRUE) 

mean(dfAll$Income, na.rm = TRUE)
dfAll$income_c <- dfAll$Income - 4.205146
mean(dfAll$income_c, na.rm = TRUE)

mean(dfAll$Edu, na.rm = TRUE)
dfAll$edu_c <- dfAll$Edu - 2.854966
mean(dfAll$edu_c, na.rm = TRUE) 

# Liberal and conservative for simple effects.
dfAll$ide_low <- dfAll$ide_c - (-30)
dfAll$ide_high <- dfAll$ide_c - (30)

# Make the belief data set for the full sample 

dfAll_Belief <- pivot_longer(dfAll, cols = c("Belief1", "Belief2", "Belief3", "Belief4"), names_to = "BeliefItem", values_to = "Belief")

dfAll_Belief

# Make the policy data set for the full sample

dfAll_Policy <- pivot_longer(dfAll, cols = c("Policy1", "Policy2", "Policy3", "Policy4", "Policy5", "Policy6", "Policy7", "Policy8", "Policy9"), names_to = "PolicyItem", values_to = "Policy")

dfAll_Policy

# Standardize data sets

zdf_All <- as.data.frame(scale(dfAll[, c("ide_c", "Age", "age_c", "Edu", "edu_c", "Income", "income_c", "WEPTcc")]), center = T)

zdf_All <- cbind(dfAll[, c("ResponseId", "Country", "cond_effects", "gend_effects", "SHAREcc"), drop = FALSE], as.data.frame(zdf_All))

# High and low ideology

zdf_All$ide_low <- zdf_All$ide_c - (-1.26) # Equal to 30 points in unstandardized units
zdf_All$ide_high <- zdf_All$ide_c - (1.26) # Equal to 30 points in unstandardized units

# Belief 

z_dfAll_Belief <- as.data.frame(scale(dfAll_Belief[, c("ide_c", "age_c", "Edu", "edu_c", "Income", "income_c", "Belief")]), center = T)

z_dfAll_Belief <- cbind(dfAll_Belief[, c("ResponseId", "Country", "BeliefItem", "cond_effects", "gend_effects"), drop = FALSE], as.data.frame(z_dfAll_Belief ))

z_dfAll_Belief

z_dfAll_Belief$ide_low <- zdf_All$ide_c - (-1.26) 
z_dfAll_Belief$ide_high <- zdf_All$ide_c - (1.26) 

# Policy

z_dfAll_Policy <- as.data.frame(scale(dfAll_Policy[, c("ide_c", "age_c", "Edu", "edu_c", "Income", "income_c", "Policy")]), center = T)

z_dfAll_Policy <- cbind(dfAll_Policy[, c("ResponseId", "Country", "PolicyItem", "cond_effects", "gend_effects"), drop = FALSE], as.data.frame(z_dfAll_Policy))

z_dfAll_Policy

```

## BELIEF ##

```{r, Ideology X Condition on Beleif in CC, Country is Random}

# Without covariates 

Belief_All1 <- lmer(Belief ~ cond_effects*ide_c + (1 | Country) + (1 | BeliefItem), data = dfAll_Belief)
summary(Belief_All1)

# Standardized

Belief_All2 <- lmer(Belief ~ cond_effects*ide_c + (1 | Country) + (1 | BeliefItem), data = z_dfAll_Belief)
summary(Belief_All2)

# With covariates 

Belief_All3 <- lmer(Belief ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1 | Country) + (1 | BeliefItem), data = dfAll_Belief)
summary(Belief_All3) 

# Extract coefficients and make a table

Belief_All3_table <- summary(Belief_All3)$coefficients %>%
                      round(., 3) %>%
                      kable()

Belief_All3_table

# Standardized

Belief_All4 <- lmer(Belief ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1 | Country) + (1 | BeliefItem), data = z_dfAll_Belief)
summary(Belief_All4)

# Extract coefficients and make a table

Belief_All4_table <- summary(Belief_All4)$coefficients %>%
                      round(., 2) %>%
                      kable()

Belief_All4_table

# Effect size conversion

ide_d <- 2 * 0.1638 / sqrt(1 - 0.1638	^2)
ide_d 
# -0.33

cond_d <- 2 * 0.0661 / sqrt(1 - 0.0661^2)
cond_d 
#0.13

int_d <- 2 * 0.0120 / sqrt(1 - 0.0120^2)
int_d
# -0.02

```

```{r, Belief graph}

# Rename condition so that neater:

dfAll$condName2[dfAll$condName == 'Control'] <- 'Control'
dfAll$condName2[dfAll$condName == 'SystemJust'] <- 'System Sanctioned Change'

Belief_Graph <- lmer(BELIEFcc ~ ide*condName2 + gend_effects + age_c + edu_c + income_c + (1 | Country), data = dfAll)
print(summary(Belief_Graph))

set_theme(theme_classic())

graph1 <- plot_model(
  Belief_Graph, 
  type = "eff", 
  terms = c("ide", "condName2"), 
  mdrt.values = 'meansd', 
  title = "A. Belief in Climate Change", 
  show.data = TRUE, 
  colors = c("darkmagenta", "cyan4"),
  dot.size = .1,
  dot.alpha = 0.3,
  axis.title = '',
  axis.labels = 'Ideology',
  legend.title = 'Condition',
  line.size = .6,
  jitter=4,
  ci.lvl = .95 # CI
)

graph1 <- graph1 +
  labs(x = "") +
  scale_x_continuous(limits = c(15, 87), breaks = c(20, 80), labels = c("Liberal/
Left Wing", "Conservative/
Right Wing")) +
  scale_y_continuous(limits = c(0, 100)) +
  theme(
    plot.margin = unit(c(0, 4.5, 0, 4.5), "cm"),
    legend.position = "none",  
    plot.title = element_text(size = 14, face = "bold", color = "black"),  
    axis.title.x = element_text(size = 14, color = "black"), 
    axis.title.y = element_text(size = 14, color = "black"),  
    axis.text.x = element_text(size = 14, color = "black"),  
    axis.text.y = element_text(size = 14, color = "black")   
  )

graph1

# ggsave("CCBeliefGraphR_63.pdf", plot = graph1, width = 8, height = 6, units = "in", dpi = 300)

```

## POLICY ##

```{r, Ideology X Condition on Policy, Country is Random}

# Without covariates 

Policy_All1 <- lmer(Policy ~ cond_effects*ide_c + gend_effects + (1 | Country) + (1 | PolicyItem), data = dfAll_Policy)
summary(Policy_All1)

# Standardized

Policy_All2 <- lmer(Policy ~ cond_effects*ide_c + gend_effects + (1 | Country) + (1 | PolicyItem), data = z_dfAll_Policy)
summary(Policy_All2)

# With covariates 

Policy_All3 <- lmer(Policy ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1 | Country) + (1 | PolicyItem), data = dfAll_Policy)
summary(Policy_All3)

# Extract coefficients and make a table

Policy_All3_table <- summary(Policy_All3)$coefficients %>%
                      round(., 2) %>%
                      kable()

Policy_All3_table

# Standardized
 
Policy_All4 <- lmer(Policy ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1 | Country) + (1 | PolicyItem), data = z_dfAll_Policy)
summary(Policy_All4)

# Extract coefficients and make a table

Policy_All4_table <- summary(Policy_All4)$coefficients %>%
                      round(., 2) %>%
                      kable()

Policy_All4_table

# Effect size conversion

ide_d <- 2 * 0.0956 / sqrt(1 - 0.0956	^2)
ide_d 
# -0.19

cond_d <- 2 * 0.0343 / sqrt(1 - 0.0343^2)
cond_d 
#0.07

int_d <- 2 * 0.0129 / sqrt(1 - 0.0129^2)
int_d
# -0.03

```

```{r, Policy Graph}

# Rename condition so that neater:
dfAll$condName2[dfAll$condName == 'Control'] <- 'Control'
dfAll$condName2[dfAll$condName == 'SystemJust'] <- 'System Justification'

set_theme(theme_classic())

Policy_Graph <- lmer(POLICYcc ~ide + condName2 + ide*condName2 + gend_effects + age_c + edu_c + income_c + (1 | Country), data = dfAll)

graph2 <- plot_model(
  Policy_Graph, 
  type = "eff", 
  terms = c("ide", "condName2"), 
  mdrt.values = 'meansd', 
  title = "B. Support for Pro-environmental Policies", 
  show.data = TRUE, 
  colors = c("darkmagenta", "cyan4"),
  dot.size = .1,
  dot.alpha = 0.3,
  axis.title = '',
  axis.labels = 'Ideology',
  legend.title = 'Condition',
  line.size = .6,
  jitter=4,
  ci.lvl = .95 # CI
)

graph2 <- graph2 +
  labs(x = "") +
  scale_x_continuous(limits = c(15, 87), breaks = c(20, 80), labels = c("Liberal/
Left Wing", "Conservative/
Right Wing")) +
  scale_y_continuous(limits = c(0, 100)) +
  theme(
    plot.margin = unit(c(0, 4.5, 0, 4.5), "cm"),
    legend.position = "none",  # Remove legend
    plot.title = element_text(size = 14, face = "bold", color = 'black'), 
    axis.title.x = element_text(size = 14, color = 'black'),  
    axis.title.y = element_text(size = 14, color = 'black'),  
    axis.text.x = element_text(size = 14, color = 'black'),  
    axis.text.y = element_text(size = 14, color = 'black')   
  )

graph2

# Save the graph
# ggsave("CCPolicyGraphR_63.pdf", plot = graph2, width = 8, height = 6, units = "in", dpi = 300)

```

## SHARING 

```{r, Ideology X Condition on Sharing, Country is Random}

# Make sure sharing is a factor 

dfAll$SHAREcc <- as.factor(dfAll$SHAREcc)

# Without covariates 

Share_All1 <- glmer(SHAREcc ~ cond_effects*ide_c + (1|Country), data = dfAll, family = binomial(link = logit))
summary(Share_All1)

# With covariates 

Share_All2 <- glmer(SHAREcc ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1|Country), data = dfAll, family = binomial(link = logit))
summary(Share_All2)

# Extract coefficients and make a table

Share_All2_table <- summary(Share_All2)$coefficients %>%
                      round(., 2) %>%
                      kable()

Share_All2_table

# Effect size conversion - r

Share_All2_r <- summary(Share_All2)$coefficients %>%
                    logoddsratio_to_r()  %>%
                    round(., 4) %>%
                    kable()

Share_All2_r  

# Effect size conversion - d

ide_d <- logoddsratio_to_d(0.0062, log = TRUE)

cond_d <- logoddsratio_to_d(0.2593, log = TRUE)

interaction_d <- logoddsratio_to_d(-0.0012	, log = TRUE)

ide_d # 0.003
cond_d # 0.14
interaction_d #-0.00

```

```{r, Sharing graph}

# Rename condition so that neater:

dfAll$condName2[dfAll$condName == 'Control'] <- 'Control'
dfAll$condName2[dfAll$condName == 'SystemJust'] <- 'System Justification'

set_theme(theme_classic())

Share_Graph <- glmer(SHAREcc ~ ide*condName2 + gend_effects + age_c + edu_c + income_c + (1|Country), data = dfAll, family = binomial(link = logit))
summary(Share_Graph)

graph3 <- plot_model(
  Share_Graph, 
  type = "eff", 
  terms = c("ide", "condName2"), 
  mdrt.values = 'meansd', 
  title = "C. Social Media Sharing Intentions", 
  show.data = TRUE, 
  colors = c("darkmagenta", "cyan4"),
  dot.size = .1,
  dot.alpha = 0.3,
  axis.title = '',
  axis.labels = 'Ideology',
  legend.title = 'Condition',
  line.size = .6,
  ci.lvl = .95, # CI
  jitter=.1
)

graph3 <- graph3 +
  labs(x = "") +
  scale_x_continuous(limits = c(15, 87), breaks = c(20, 80), labels = c("Liberal/
Left Wing", "Conservative/
Right Wing")) +
  scale_y_continuous(limits = c(0, 1)) +
  theme(
    plot.margin = unit(c(0, 4.5, 0, 4.5), "cm"),
    legend.position = "none",  # Remove legend
    plot.title = element_text(size = 14, face = "bold"),
    axis.title.x = element_text(size = 14, color = 'black'),  
    axis.title.y = element_text(size = 14, color = 'black'),  
    axis.text.x = element_text(size = 14, color = 'black'),  
    axis.text.y = element_text(size = 14, color = 'black')   
  )

graph3


# Save the graph
# ggsave("CCShareGraphR_63.pdf", plot = graph3, width = 8, height = 6, units = "in", dpi = 300)

```

## ACTION ## 

```{r, Ideology X Condition on Action, Country is Random}

# Without covariates 

Action_All1 <- lmer(WEPTcc ~ cond_effects*ide_c + (1|Country), data = dfAll)
summary(Action_All1)

# Standardized

Action_All2 <- lmer(WEPTcc ~ cond_effects*ide_c + (1|Country), data = zdf_All)
summary(Action_All2)

# Add covariates

Action_All3 <- lmer(WEPTcc ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1|Country), data = dfAll)
summary(Action_All3)

# Extract coefficients and make a table
Action_All3_table <- summary(Action_All3)$coefficients %>%
                      round(., 2) %>%
                      kable()

Action_All3_table

# Standardized 

Action_All4 <- lmer(WEPTcc ~ cond_effects*ide_c + gend_effects + age_c + edu_c + income_c + (1|Country), data = zdf_All)
summary(Action_All4)

# Extract coefficients and make a table
Action_All4_table <- summary(Action_All4)$coefficients %>%
                      round(., 3) %>%
                      kable()

Action_All4_table

```
